
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./user-service/src/main/resources:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8082:8080"
    depends_on:
      - postgres

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/user_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    develop:
      watch: 
        - path: ./user-service/src
          target: /app/src
          action: sync+restart
        - path: ./user-service/pom.xml
          target: /app/pom.xml
          action: rebuild

volumes:
  pgdata:
